### ISSUE TITLE
active borders overflow on icon buttons

### ISSUE THREAD

**Issue by cdaringe** [Tripwire/octagon#117]
# problem statement

this doesn't appear to look right

![untitled mov](https://user-images.githubusercontent.com/1003261/29945150-e800e4de-8e54-11e7-8b12-729ff32b7237.gif)

# discussion

- are we sure we want active borders?  i've never seen this before

**Comment by ggascoigne** [comment]
Do you mean "should we have them" on icon buttons specifically, or all of the buttons in general?

How should we show active or focus on icon buttons instead?

**Comment by cdaringe** [comment]
i have seen this before, i was just mistaken, so please forgive that remark.

i suppose what is necessary is a default margin that compensates for the shadow overflow?  @andrewleyva  may have input here
