### ISSUE TITLE
semantic-ui dependency is intrusive, heavy, and slow

### ISSUE THREAD

**Issue by cdaringe** [Tripwire/octagon#119]
# problem statements

- the `semantic-ui` npm dependency is unconventional, wherein on update, it modifies our source code in `semantic/*` paths.
  - this leads to unexpected updates the source while you are working with deps (yah, we could pin it, but we shouldn't have to)
- the `semantic-ui` npm dependency ships a full build toolchain in `semantic/*` in the form of gulp and gulp tasks
  - we have to use these gulp tasks to build our CSS, fonts, and small images, as well as watch and build when in dev mode
  - these are heavy, slow, and have to be executed in a separate process

# solution path

https://github.com/Semantic-Org/Semantic-UI-LESS

- update our build process to just call `less` to build a static copy of our theme
- update our styleguide (which is not part of our formal build) to use `[less-loader](https://www.npmjs.com/package/less-loader)` to build/watch our theme for the styleguide.

**Comment by andrewleyva** [comment]
Resolved by
1) replacing Semantic UI with Semantic UI Less. 
2) Build is done in temporary build file merging our theme and assets with SUIR
3) Watcher in build process detects changes and relaunches build process
Note: Less Loader was not used.

**Comment by Asgator** [comment]
@andrewleyva Hello! Can are you plz show your webpack.config where build fast?

**Comment by pagesrichie** [comment]
@andrewleyva I'm still unclear as to the solution.. how do we speed up Semantic UI LESS builds exactly?

**Comment by andrewleyva** [comment]
Sorry, I'm not sure what you're asking. We refactored the build. There is nothing for you to do.
