### ISSUE TITLE
Bundle size is too big

### ISSUE THREAD

**Issue by ggascoigne** [Tripwire/octagon#120]
When examining the size of this bundle in a CRA app that uses octagon it appears that all of SUIR gets included regardless of just how much we end out calling.

This is based on using source-map-explorer.  I'd like to know if there's some way to minimize just how much of SUIR we include.

**Comment by cdaringe** [comment]
@andrewleyva, this issue is getting some heat.  if you have time to dig into it, that'd be very helpful.

**Comment by cdaringe** [comment]
@youngbob found that his bundle was >100kBs.  i observed that ~~all of lodash and SUIR seem to get bundled just by including, say, a single checkbox.  diagnosing means tracing the import tree.  i believe webpack has some tooling to explain imports that would be helpful.  my `snitch` app also traces the dependency graph and explains imports.

**Comment by andrewleyva** [comment]
Nice. Yay peer dependency.

**Comment by cdaringe** [comment]
just adding a cross ref.

sizes will go down when these issues close: https://github.com/Tripwire/octagon/issues/185#issuecomment-386429527

and when using 11.x of this lib and newer.  these things will all collectively enable CRA tree-shaking
