### ISSUE TITLE
Update to use current UX defined Palette

### ISSUE THREAD

**Issue by ggascoigne** [Tripwire/octagon#121]
The palette used by Octagon differs from current TW UX guidelines, we should upgrade it.

Specifically, twgrey is no longer to be used, we've generally replaced this with #28324E except where we've used one of #A6A8AB or #28324E.

This will need some review by TOC as well as UX teams.

**Comment by cdaringe** [comment]
iirc, none of this really follows the guideline right? i thought the guideline was Yung's theme?

**Comment by ggascoigne** [comment]
YeEs, it probably is Yung's theme, but either way, octagon doesn't follow it.
