### ISSUE TITLE
Octagon not publishing to NPM (only Gh)

### ISSUE THREAD

**Issue by andrewleyva** [Tripwire/octagon#158]
This happened when we switched from Codeship to CircleCI because of the way they differ in env variable injection.
There are a couple of parts to this: Update verify condition, update env variable...

**Comment by andrewleyva** [comment]
I believe these two PRs are related to the fix:
https://github.com/Tripwire/octagon/pull/156
https://github.com/Tripwire/octagon/pull/157

**Comment by cdaringe** [comment]
& https://github.com/Tripwire/octagon/pull/159

**Comment by cdaringe** [comment]
Fixed!

**Comment by andrewleyva** [comment]
Verbally Approved yesterday. Adding +1 after the fact. Meh.
