### ISSUE TITLE
where shall we document component usage

### ISSUE THREAD

**Issue by cdaringe** [Tripwire/octagon#16]
# problem

- components need documentation.  an API reference would be great

# discussion

#6 already has the action for proxying all imported SUIR component docs into the storybook for those components that we import (s.t. we dont provide _two_ sources of truth for what components we export). hence, i am of the opinion that ya, lets put docs into storybook.

im super open to static analyzers that take doc blocks from the components & create docs too.  IIRC, there may be a plugin for this.  i need to jump on my bike, but lets discuss!

**Comment by cdaringe** [comment]
this would be toooo raaaad, https://github.com/storybooks/react-storybook/issues/602

**Comment by eddier** [comment]
Depending on the timeline for the above script we could use the doc-gen plugin to provide some the configuration options available to components.  https://github.com/kadira-samples/react-storybook-docgen-info-sample

**Comment by eddier** [comment]
Alternatively is storybook providing any advantage compared to using [Styleguidist](https://github.com/styleguidist/react-styleguidist) exclusively?

**Comment by eddier** [comment]
@cdaringe  this is an example of one of the existing custom components using the Styleguidist approach - if you want to check out how this might work in practice I can check this branch in.

![image](https://cloud.githubusercontent.com/assets/1723648/23284923/e3e9928a-f9e2-11e6-862b-8d43ea45f21b.png)

**Comment by cdaringe** [comment]
hey @eddier, that looks saweeeet.  very interested!  lets try it youre down!

**Comment by cdaringe** [comment]
sorry for the lagged responses again, FYI. busy day!

**Comment by eddier** [comment]
It's on the styleguide branch, check it out and install dependencies then yarn run styleguide.  Let me know what you think.

**Comment by cdaringe** [comment]
it launched & ran _great!_  lets discuss paths forward. i see a few options.

- no storybook, just styleguidist.
  - this ostracizes UX, who is a first class customer & needs viz as the lib changes
    - i.e. there isnt a "storybook-hub" tool for styleguidist to integrate them into the reviews easily
- no styleguidist, just storybook
  - lose out on interactivity & rich API docs
    - those API docs are too good to lose!
  - still could benefit from the component docs because of https://github.com/kadirahq/babel-plugin-react-docgen
- use both
  - still get the benefits of both, but have a duplicate build temporarily to serve developers

im in favor of using both (option 3), with the intent to drop the standalone styleguidist in the high hopes that the storybook integration becomes a thing™.

thoughts? @Tripwire/octagonners

**Comment by cdaringe** [comment]
@eddier , `undefined`s are a little strange

```
$ yarn run styleguide
yarn run v0.21.0
$ styleguidist server
Style guide server started at:
http://localhost:3000


src/styles/components/pagination-control.css
undefined [undefined]


src/styles/components/favorite-button.css
undefined [undefined]


src/styles/app.css
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]

Compiled successfully!
```

**Comment by eddier** [comment]
Yeah I figured we make a call on direction then we iron out any issues with the selected approach assuming it includes styleguidist.

**Comment by jhegg** [comment]
> im in favor of using both (option 3), with the intent to drop the standalone styleguidist in the high hopes that the storybook integration becomes a thing™.

That sounds like a good plan to me.

**Comment by eddier** [comment]
Sounds good.  I've updated that branch with the following:

-  Section for custom components
  - examples are automatically tracked as '<component>.examples.md'

- Section for SUI based components
  - examples are tracked in the /styleguide/<component>.examples.md'
  - examples have to be manually entered which is probably ok given that there are not a ton and not all    SUI components should be included in this, only extended ones.

**Comment by cdaringe** [comment]
merged!
