### ISSUE TITLE
The pagination control is misusing the not-allowed cursor

### ISSUE THREAD

**Issue by ggascoigne** [Tripwire/octagon#167]
Currently the disabled pagination buttons (e.g. the back button when you are on page 1) change the mouse cursor to use the not-allowed cursor.  I think that this is unnecessary, looks particularly ugly (the cursor is red on WIndows Firefox for example), and it implies the wrong thing to the user.

Most elements on a web page are already non-clickable, so much so that we indicate that something **is** clickable by changing the cursor to be a hand pointer rather than the arrow pointer.  Disabled buttons take this a step further, since they have an appearance that tells the user that they are clickable, when they are disabled they get a modified look that 'disables' them, and they go back to just using the arrow pointer.

The not allowed cursor is designed for drag and drop behavior when you are emphasizing an invalid drop target, and that's where it should stay.

The disabled buttons in the pagination control are already disabled, they already look non-clickable, they don't need that do-not-drop (not-allowed) mouse cursor added as well.

**Comment by cdaringe** [comment]
im ok with removing `not-allowed` and moving to `initial` or whatever

**Comment by andrewleyva** [comment]
@ykohux @antoinejuhel 
you okay with removing `not-allowed` and using `default`?

**Comment by antoinejuhel** [comment]
I want to speak to @ykohux before we do anything. For now I don't want to change anything.

**Comment by andrewleyva** [comment]
FYI
Windows 10 Edge
![win10-edge-pag-not-allowed](https://user-images.githubusercontent.com/1317206/36332271-758e3f74-1369-11e8-97fc-27010d5acae7.png)

Windows 10 Firefox
![win10-ff-pag-not-allowed](https://user-images.githubusercontent.com/1317206/36332277-7de9a316-1369-11e8-8111-71b63b42335b.png)

**Comment by andrewleyva** [comment]
Issue closed. Design meets UX spec.
