### ISSUE TITLE
define test strategy

### ISSUE THREAD

**Issue by cdaringe** [Tripwire/octagon#17]
# problem

- we need a test strategy for inbound components

# discussion

- some test config is already defined.  we can do some assertions on some input sets there, or, visualize those same inputs & just use automated snapshotting. https://github.com/storybooks/storyshots

**Comment by eddier** [comment]
Take a look at https://github.com/garris/BackstopJS for an option that will do UI regression testing.  Let me know what you think.

**Comment by cdaringe** [comment]
confirmed, no flex sppt in phantom 2.x. bummer!

**Comment by cdaringe** [comment]
https://github.com/jonathantneal/flexibility ?

**Comment by cdaringe** [comment]
backstop agreed upon.  chasing that independently in #37
