### ISSUE TITLE
Checkbox SUIR component imported from wrong path

### ISSUE THREAD

**Issue by pfaffle** [Tripwire/octagon#172]
The Checkbox component that we [wrap and re-expose](https://github.com/Tripwire/octagon/blob/master/src/components/suir/checkbox/Checkbox.js#L1) is importing the wrong source file, from a path that doesn't exist. It may have been moved at some point.

As you can see here, the file exists in modules/Checkbox rather than elements/Checkbox:
![image](https://user-images.githubusercontent.com/564302/37423645-a233a520-277b-11e8-8ca2-0a9860cdd802.png)

Theoretically, the Storybook should have caught this error, but the component is displayed correctly there. It appears that the reason for that is because we are importing it directly from semantic-ui-react rather than from our own library (https://github.com/Tripwire/octagon/blame/master/src/components/suir/checkbox/Checkbox.examples.md#L3). A number of our Storybook examples follow this pattern. I suspect those ought to be changed so that they're using our re-exported components to prove we're doing it right.

**Comment by cdaringe** [comment]
Per team discussion, all examples/tests should pull from shipped artifacts.
