### ISSUE TITLE
Data-hooks are added inconsistently to Octagon components. We need an agreed upon solution

### ISSUE THREAD

**Issue by andrewleyva** [Tripwire/octagon#175]
# Problem: 
Data-hooks are added inconsistently (and with different key namings). Sometimes we add them in the app, sometimes in the component. We need a pattern that takes into account the needs of our systems. 

# Discussion:
QA needs data-hooks to easily access components or features within a component. I believe we should standardize the naming of the data-hook and the pattern around adding one.
A) Currently we have TOC using "data-hook" and Connect using "data-test-hook". Let's pick one and use it for both apps. This will enable Octagon to provide more robust solutions by including hooks for QA. (I'd vote "data-hook" because it's shorter.)
B) Currently, we often add our data-hooks to components in the apps. Sometimes, this solution is limiting since QA may need to access a feature within a component (e.g. Pagination has 4 buttons and 1 input box). For this discussion, we have 2 types of components (1) Simple and (2) Complex. I'm defining Simple as a component with one access point for QA where that access point is the surface area exposed to the app.

1) In the Simple case, the app can easily add the data-hook. It may be desirable to add the data-hook within the component, but in the case of SUIR this will mean adding an abstraction layer to enhance/modify the component. 
2) In the Complex case, we need multiple data-hooks so QA can access all the features of the component (e.g. Pagination). For some of these components, we have a degree of confidence that only one will exist per page, and have allowed for a generic data-hooks (e.g. data-hook="pagination-button-next-page"). However, if we don't have this guarantee, we need a more robust solution. 

# Potential Solutions:
A) Naming: Perhaps naming should be "data-hook" (get Connect to update).
B) Adding Data Hooks
For all Simple components, the app will add the data-hook. For Complex components we have basic two options:
1) We create data-hooks dynamically. This could be done possibly be pushing an ID through as a prop, and then naming the data-hook on the fly (e.g. result: data-hook="table1--pagintion-button-next-page").
2) QA will call a generic data-hook to access the component, and will move down the DOM to the appropriate feature. Where there are multiple Complex X components on a page they will need to specificy the ID to reach the correct component (e.g. "#table1 .pagination > .button-next-page"). I'm not a fan of this because my understanding is that data-hooks are supposed to remove the complexity of accessing our components. If we went this route, possibly we could just get rid of data-hooks all together and require good naming of IDs and classes.

**Comment by cdaringe** [comment]
1. in retro, we **shouldn't add test hooks at all**, but we should just enable them.  let the consuming project use what they want.  for instance, we've been using cypress.io, which [likes `data-test`](https://docs.cypress.io/guides/core-concepts/test-runner.html#Uniqueness)
    1. this removes a lot of the complexity you discuss
1. for what you're calling `complex` components either:
    1. our API should take blessed sub-components as children, rather than rendering them directly on behalf of the consumer (see ex1 below), or
    1. make testers use other means (e.g. xpath) to get at what they need.
        1. clearly we need to support testing, but getting a hook on every node is not sustainable


```jsx
// ex1

// preferred, for agility reasons and so now they can put whatever attr's they want on it
<Menu>
  <Menu.Item data-test-hook='bananas'> ...</...>
</Menu>

// also OK
<Menu items=[<Menu.Item data-test-hook='bananas'> ...</...>, ...] />

// less preferred
<Menu items=[{ pojo }, ... {} />
```

**Comment by cdaringe** [comment]
now that we more rigorously proxy props thru, this issue is entirely on consumers.  closing for now.  re-open if y'all feel like we need to have further discussion
