### ISSUE TITLE
drop unnecessary postcss-neat

### ISSUE THREAD

**Issue by cdaringe** [Tripwire/octagon#183]
# problem

`postcss-neat` is neat, but obsolete.  we can just use css grid or flexbox

# discussion

we use the neat plugin _very sparingly_.  let's clean house and trash it: http://jo-asakura.github.io/postcss-neat/demo.html

**Comment by andrewleyva** [comment]
Makes sense. +1

**Comment by andrewleyva** [comment]
closed by #222
