### ISSUE TITLE
Default export missing SUIR components

### ISSUE THREAD

**Issue by benjspriggs** [Tripwire/octagon#188]
# Overview
As of v10.0.0, running `npm run build` will give a production `lib/` missing some SUIR exports:

- Checkbox
- Dimmer
- Dropdown
- Label
- Loader
- Modal
- Popup
- Progress
- Radio

This looks like what gets published to npm, and I'd like to be able to use SUIR components bundled in react-octagon instead of digging into `lib/components/suit/something/Something`.

**Comment by cdaringe** [comment]
Thanks!  Because we intend to execute https://github.com/Tripwire/octagon/issues/185, we are unlikely to pursue this.  The effort is much appreciated--sorry to incur it upon you!
