### ISSUE TITLE
Minimized css in dist build

### ISSUE THREAD

**Issue by youngbob** [Tripwire/octagon#205]
The final build only contains `semantic.css` and not a minimized `semantic.min.css`

Since there are a lot of "theme" comments all over, the size savings is probably noticeable.

**Comment by cdaringe** [comment]
Iirc, most bundlers will minify during prod builds.  It would seem to me at dev time, folks actually want the non minified version.

**Comment by youngbob** [comment]
You're right, the final build of my app is minimized.

¯\\\_(ツ)\_/¯
