### ISSUE TITLE
Inconsistent button styling

### ISSUE THREAD

**Issue by benjspriggs** [Tripwire/octagon#218]
## overview

Submit buttons are significantly different from normal buttons, especially ones with `href` links. Ideally, buttons shouldn't look significantly different whether or not they submit data or call a callback.

### button with href

![screen shot 2018-06-07 at 11 15 18 am](https://user-images.githubusercontent.com/7821629/41118210-1edbe528-6a44-11e8-99d8-dc5946a164fe.png)

### submit button

![screen shot 2018-06-07 at 11 12 17 am](https://user-images.githubusercontent.com/7821629/41118119-e4b85d18-6a43-11e8-8536-559e21d59bb9.png)

### submit button with href

![screen shot 2018-06-07 at 11 12 29 am](https://user-images.githubusercontent.com/7821629/41118124-e7c64498-6a43-11e8-94ad-48f902e42776.png)

**Comment by andrewleyva** [comment]
adding type=submit creates the default style rule: "-webkit-appearance: button;"
Our buttons should default to: "-webkit-appearance: inherit;" to solve this.
