### ISSUE TITLE
Update to SUIR 0.81 and SUI CSS 2.3

### ISSUE THREAD

**Issue by youngbob** [Tripwire/octagon#221]
SUIR 0.81 is out, and updates everything to SUI 2.3, so both dependencies need to be updated.

Interestingly, there is a devDependency on 0.81 already, but the peerDependency is still on 0.79 (and SUI CSS is 2.2)

**Comment by youngbob** [comment]
See SUIR issue: Semantic-Org/Semantic-UI-React/pull/2657

**Comment by cdaringe** [comment]
@andrewleyva, can you bite this one off next?

**Comment by cdaringe** [comment]
@youngbob noted that this upgrade affected Dimmer and Modal.  maybe we can test some examples of those with such a PR?
