### ISSUE TITLE
SUI theme needs updating for latest font-awesome

### ISSUE THREAD

**Issue by youngbob** [Tripwire/octagon#252]
There are significant differences between the current default SUI theme for icons and what we have. Some icons appear to just be broken. This is likely due to the apparent upgrade from Font Awesome 4.x to 5.x.

It's not clear to me what we are trying to override for icons in our theme. Can we just get rid of the override? It looks like @andrewleyva added this originally.

**Comment by cdaringe** [comment]
also, added a screenshot test for this.  https://tripwire.github.io/octagon/#icon
