### ISSUE TITLE
Input error class does not work as expected

### ISSUE THREAD

**Issue by youngbob** [Tripwire/octagon#259]
With the default SUI theme, adding the "error" class adds a red border and a light-red background. The octagon theme override seems to prevent that from happening, so there is no visual indication of an error state. Also, any placeholder text disappears (for reasons I don't understand).

The error state appears to work for some other SUIR controls, such as Dropdown, but not Input.

Dropdown error state:
![screen shot 2018-07-26 at 10 31 13 am](https://user-images.githubusercontent.com/2251274/43268708-51fc7cf0-90bf-11e8-9b90-408eb7d19092.png)

Input error state (octagon):
![screen shot 2018-07-26 at 10 33 34 am](https://user-images.githubusercontent.com/2251274/43268731-5ea5a260-90bf-11e8-8d6c-63d90b2b67f8.png)

Input error state (default):
<img width="190" alt="screen shot 2018-07-26 at 10 34 05 am" src="https://user-images.githubusercontent.com/2251274/43268780-799e3028-90bf-11e8-85be-47ca449c94c2.png">

**Comment by youngbob** [comment]
Without the surrounding `<Form>` tag, the behavior is a little different. You get a red border, unless the field is focused, then the blue focuesed state takes precedence. The placeholder text still disappears

```jsx
const Input = require('semantic-ui-react').Input;
<div>
    <div>Normal</div>
    <Input placeholder="Normal" />
    <br />
    <div>Error</div>
    <Input error placeholder="Error" />
    <br />
    <div>Focus</div>
    <Input focus placeholder="Focus" />
    <br />
    <div>Disabled</div>
    <Input disabled placeholder="Disabled" />
</div>
```

<img width="205" alt="screen shot 2018-07-26 at 3 52 51 pm" src="https://user-images.githubusercontent.com/2251274/43285169-1d3d783e-90ec-11e8-88ab-1a374a734dd1.png">

**Comment by youngbob** [comment]
With the surrounding `<Form>` tag, I get no red border and no placeholder.
Adding `<Form.Field>` around each `<Input>` makes them fill the container width, but does not change the styling otherwise.

```jsx
const Form = require('semantic-ui-react').Form;
const Input = require('semantic-ui-react').Input;
<Form>
    <Form.Field>
    <div>Normal</div>
    <Input placeholder="Normal" />
    </Form.Field>
    
    <Form.Field>
    <div>Error</div>
    <Input error placeholder="Error" />
    </Form.Field>
    
    <Form.Field>
    <div>Focus</div>
    <Input focus placeholder="Focus" />
    </Form.Field>
    
    <Form.Field>
    <div>Disabled</div>
    <Input disabled placeholder="Disabled" />
    </Form.Field>
</Form>
```

<img width="921" alt="screen shot 2018-07-26 at 3 59 29 pm" src="https://user-images.githubusercontent.com/2251274/43285465-01d24eac-90ed-11e8-956b-44e7de1aaaa0.png">

**Comment by cdaringe** [comment]
`error` shall be placed on `<Form.Field />` instead of `<Input />`
