### ISSUE TITLE
ThinCard props behave opposite of expected

### ISSUE THREAD

**Issue by youngbob** [Tripwire/octagon#261]
This may just be an issue of opinion, but ThinCard's `folder` and `noBorder` props do not make sense to me.

### folder

This shouldn't default to `true`, since it's a modifier.

ThinCard with a folder tab:
```jsx
<ThinCard folder />
```

(Expected) ThinCard without a folder tab:
```jsx
<ThinCard />
```
Actually still renders ThinCard with a folder.

(Actual) ThinCard without a folder tab:
```jsx
<ThinCard folder={false} />
```
This seems somewhat unusual, and isn't how other components (SUIR) behave.

### noBorder

In general, boolean values shouldn't be "not something".

**Comment by cdaringe** [comment]
strong agree.
