### ISSUE TITLE
react-scripts@2.0.0 does not import semantic.css

### ISSUE THREAD

**Issue by youngbob** [Tripwire/octagon#297]
Using react-scripts@2.0.0 and importing `react-octagon/lib/styles/semantic.css`, the SUI styles are not actually included in the final .css output of the build. Though, confusingly, the styles appear fine when running a dev server.

Importing the "vanilla" version from semantic-ui-css works fine.

I assume something about how the semantic.css file is packaged is confusing Webpack and making it think it isn't a valid .css file or something.

**Comment by cdaringe** [comment]
@youngbob, want to close this and just track it over in the react-scripts issue tracker?

**Comment by youngbob** [comment]
I'd rather wait and see what the result of that is. If it turns out there is an issue that can/should be fixed in octagon, we should leave this open. If they accept full responsibility and fix it, then we'll just close this out.
