### ISSUE TITLE
fontawesome is referenced in icon.overrides, yet missing

### ISSUE THREAD

**Issue by jhegg** [Tripwire/octagon#33]
I think fontawesome was removed from the vendored bits, but was not replaced with the package dependency. Should it be?

**Comment by jhegg** [comment]
@cdaringe @eddier I'm not sure (or if) to fix this, any idea?

**Comment by cdaringe** [comment]
yea looks like it's missin!

i installed the npm package:

```
$ tree node_modules/font-awesome/fonts/
node_modules/font-awesome/fonts/
├── FontAwesome.otf
├── fontawesome-webfont.eot
├── fontawesome-webfont.svg
├── fontawesome-webfont.ttf
├── fontawesome-webfont.woff
└── fontawesome-webfont.woff2
```

@eddier, I dont recall what the import should look like.  its not in site.overrides or icon.overrides.  https://github.com/Tripwire/octagon/blob/master/semantic/src/themes/tripwire/globals/site.overrides .  if you can advise as to what the font import statement is, i can update the build script?

**Comment by eddier** [comment]
I could be wrong, but doesnt SUI use their flavor of font that is in themes/tripwire/assets/fonts/ ?  It should be labeled as icons.eot, svg, ttf,woff, woff2.  When including the octagon lib you should be able to render a FA icon by using the syntax <Icon name="users" /> and it should work.  Is it not?

**Comment by jhegg** [comment]
For example, `user circle` and `user circle outline` are just circles, and `user outline` is just a user. Here I'm using the following:

```js
<Icon className='user plus' />
<Icon className='user circle' />
<Icon className='user circle outline' />
<Icon className='user outline' />
<Icon className='user' />
<Icon className='users' />
```

![image](https://cloud.githubusercontent.com/assets/3254856/23635549/55904622-0285-11e7-9baa-00f70c26ea44.png)

The rendered style should be `i.icon.user.circle:before {}`, and not `i.icon.circle:before {}`.

**Comment by eddier** [comment]
I think this may be a SUI issue rather than an issue with Octagon.  Check out the example in their issues:
https://github.com/Semantic-Org/Semantic-UI-React/issues/1371

**Comment by jhegg** [comment]
Got it. Closing for now. :smile:

**Comment by cdaringe** [comment]
doh! thx :)
