### ISSUE TITLE
suir prop-type warning on bell icon

### ISSUE THREAD

**Issue by cdaringe** [Tripwire/octagon#333]
# problem

https://github.com/Tripwire/octagon/blob/571bb4aa436164f58e71ed0de356812e36842c0e/src/components/Notification/NotificationEmpty.jsx#L10 uses class `bell_icon`, which violates SUIR's `propType`s-like-thing

<img width="604" alt="image" src="https://user-images.githubusercontent.com/1003261/48824184-5ec88e00-ed18-11e8-9753-ffb2fe8c0f6c.png">

**Comment by andrewleyva** [comment]
I think there was a typo here and the attribute should be className. Does that sound correct @GirishSarbhukan?

**Comment by GirishSarbhukan** [comment]
Perfect, ideally it should be <Icon name='bell outline' className={'bell_icon'} size='big' />
I think name property just represent the type of icon being used, so additional bell_icon icon needs to be added using className.
