### ISSUE TITLE
handled prop passed thru as unhandled prop on NotifcationBody

### ISSUE THREAD

**Issue by cdaringe** [Tripwire/octagon#334]
# problem

the prop `selectedNotification` gets passed thru to the element here: https://github.com/Tripwire/octagon/blob/master/src/components/Notification/NotificationBody.jsx#L44

this is invalid, and should be handled.  one option could be to wire up https://github.com/layershifter/babel-plugin-transform-react-handled-props.  I'm a little iffy on that though.  it's a bit of hidden magic and probably isn't super TS friendly.  it's not too much effort/cost to just _handle_ these

**Comment by andrewleyva** [comment]
it was probably supposed to be passed through explicitly and got missed. thanks for catching that @cdaringe.
hope the new gig is going well and that you're "rolling back the technical debt' #badjoke #sorrynotsorry
