### ISSUE TITLE
BarChart axis labels missing?

### ISSUE THREAD

**Issue by jhegg** [Tripwire/octagon#34]
I wanted to add x-axis data labels to my usage of BarChart, but it doesn't appear to be implemented. Is it possible to add that?

For example, I want a bar chart where each x-value is a text label of a day (`Mon`, `Tue`, `Wed`, etc), and the y-value is some number.

**Comment by eddier** [comment]
Sounds good I can add these, is there any other content you want to make available to this graph?

**Comment by jhegg** [comment]
One other thing on the BarChart is that we need the ability to overlay an icon on each bar. For example, this could be vertically centered within each bar, and the icon is tied to the warning/error state. So if it's yellow/orange then it's a warning, if it's red it's an error icon. If the bar is too small, then it would be nice for the icon to float above it (since it wouldn't fit inside).

Does that make sense?

**Comment by eddier** [comment]
ok I'll check it out.

**Comment by jhegg** [comment]
Here is an example:

![bar-chart-with-icons](https://cloud.githubusercontent.com/assets/3254856/24010879/4f047892-0a36-11e7-9d24-e987bdf457c1.png)

**Comment by jhegg** [comment]
This was addressed per #52 .
