### ISSUE TITLE
Enable branch protection on this repo

### ISSUE THREAD

**Issue by youngbob** [Tripwire/octagon#349]
I have admin rights to do this myself, but wanted to open this issue for discussion.

I think we should enable branch protection on the master branch for this repo, so that changes cannot be merged to master without a code review and tests passing.

Thoughts? @andrewleyva @ggascoigne

**Comment by andrewleyva** [comment]
Absolutely. Good call.

**Comment by youngbob** [comment]
Ok, enabled. We can adjust the rules later if they turn out to be too painful.

**Comment by andrewleyva** [comment]
Do we want to add an ADR to document this decision @youngbob @ggascoigne
