### ISSUE TITLE
start stop button are different sizes

### ISSUE THREAD

**Issue by cdaringe** [Tripwire/octagon#35]
![ssbutton](https://cloud.githubusercontent.com/assets/1003261/23635063/655a3bce-0282-11e7-9ca1-1b5fcfc5189e.gif)

the diameter is juuuuuussst a few pixels off, even though the node size is equivalent

**Comment by eddier** [comment]
I saw this as well.  The Elegant font icon for the pause symbol has a larger diameter than the play icon which causes this.  At least that is what I can tell...

**Comment by cdaringe** [comment]
design voided
