### ISSUE TITLE
Left Navigation

### ISSUE THREAD

**Issue by eddier** [Tripwire/octagon#46]
Fragments TBD

Should handle router active state for n number of menu items

**Comment by eddier** [comment]
@cdaringe in the prototype this relies on react-router, are you ok with bringing that dependency into octagon?

**Comment by cdaringe** [comment]
I have preference to not.  Do you feel like its too difficult otherwise?  I figure the nav could exist on its own w/out any `Link`s.  Then as we add nav items, we could bind those in our app code to routes

**Comment by eddier** [comment]
That should be fine.
