### ISSUE TITLE
button sizes

### ISSUE THREAD

**Issue by devongleeson** [Tripwire/octagon#48]
Hello, it seems like the button vertical sizes for negative and positive buttons are not the same. So when they are on the same line they look funky.

```
<Flexbox>
	<Form.Button
	  negative
	  data-hook={`cancel-generate-supervisor-button`}
	  onClick={this.handleClose}>Generate Supervisor
	</Form.Button>
	<Form.Button primary
	  type='submit'
	  disabled={!valid || submitting}
	  data-hook={`generate-supervisor-button`}>Generate Supervisor</Form.Button>
</Flexbox>
```
![image](https://cloud.githubusercontent.com/assets/11401188/24062908/a0765fa8-0b1a-11e7-9ee3-f1f15ed94bd3.png)

**Comment by eddier** [comment]
Try adding the className prop of 'tripwire' while using the type of positive rather than primary.  Example:

<Form.Button positive
          className='tripwire'
	  type='submit'
	  disabled={!valid || submitting}
	  data-hook={`generate-supervisor-button`}>Generate Supervisor</Form.Button>

**Comment by devongleeson** [comment]
We tried changing it, as suggested, but are still seeing differently rendered sizes.

```
<Flexbox>
	<Form.Button
	  className='tripwire'
	  negative
	  data-hook={`cancel-generate-supervisor-button`}
	  onClick={this.handleClose}>Cancel
	</Form.Button>
	<Form.Button
	  className='tripwire'
	  positive
	  type='submit'
	  disabled={!valid || submitting}
	  data-hook={`generate-supervisor-button`}>Generate Supervisor</Form.Button>
</Flexbox>
```

![image](https://cloud.githubusercontent.com/assets/11401188/24063201/ee4f53e6-0b1b-11e7-9004-64359a80e355.png)

**Comment by eddier** [comment]
That isn't applying the tripwire class to the actual button element.  Can you call it following the styleguidist example?  So it would be:

<Button
	  className='tripwire'
	  positive
	  type='submit'
	  disabled={!valid || submitting}
	  data-hook={`generate-supervisor-button`}>Generate Supervisor</Button>

**Comment by devongleeson** [comment]
Yes, that worked!  Thanks.

**Comment by ggascoigne** [comment]
So is this a work around or an expected behavior?  Seems odd to have to explicitly specify what I'd expect to just be the theme default.

**Comment by eddier** [comment]
Since the SUI button component has so many variations it doesn't seem like a good idea to change the default behavior, that's why we chose to implement it as a class that the developer can activate.  This retains all of the default SUI button styling for future use if desired.
