### ISSUE TITLE
document in <Welcome /> preferential usage

### ISSUE THREAD

**Issue by cdaringe** [Tripwire/octagon#5]
e.g. dont write your own DOM!

@joshuasleeper

**Comment by joshsleeper** [comment]
Basically, it'd be nice to compare and contrast the benefits similar components provide and try to stick to a reasonable subset to as to avoid having an excessive variety of ways to do the exact same thing.

tl;dr
Minimal options,; maximum flexibility.

**Comment by cdaringe** [comment]
closed by #21.  eager closing
