### ISSUE TITLE
BarChart breaks when mouseover happens

### ISSUE THREAD

**Issue by jhegg** [Tripwire/octagon#50]
In both FireFox and Chrome, when I mouseover the [BarChart](https://tripwire.github.io/octagon/#!/BarChart/1) it breaks by collapsing down into one wide column.

Before mouseover:
![image](https://cloud.githubusercontent.com/assets/3254856/24113599/8ac3efee-0d5a-11e7-97f3-c09931021293.png)

After mouseover:
![image](https://cloud.githubusercontent.com/assets/3254856/24113626/a2c54f0c-0d5a-11e7-9f03-7b431cf6b15e.png)

**Comment by eddier** [comment]
This will be fixed as part of the new labels/icon support for the bar graph.

**Comment by jhegg** [comment]
@eddier Great, thank you! 😄

**Comment by eddier** [comment]
Check #52 for fix.

**Comment by eddier** [comment]
@jhegg does that PR fix this issue for you?

**Comment by jhegg** [comment]
Yep, it does!
