### ISSUE TITLE
npm link to a create-react-app project requires url-loader

### ISSUE THREAD

**Issue by ggascoigne** [Tripwire/octagon#55]
When linking to the react-octagon source from a create-react-app generated project, I end out having to add url-loader as a dev dependency to react-octagon. I don't really understand the loading  behavior here. :)

**Comment by eddier** [comment]
I noticed that as well, I thought it was added to the octagon lib a while back.  Can you retry this with the LeftNav branch and see if it works properly for you now?

**Comment by ggascoigne** [comment]
yes, that fixes it.  Thanks.

**Comment by eddier** [comment]
closed by #54
