### ISSUE TITLE
Barchart column labels need to more configurable

### ISSUE THREAD

**Issue by ggascoigne** [Tripwire/octagon#56]
Is there a way to change the font size of the bar chart labels?

using
```
<BarChart
                    barPadding={0.2}
                    borderRadius={0}
                    data={dataBarChart}
                    height={100}
                    width={this.state.chartWidth}
                    xDataType='date'
                    showXLabel
                    showIcon
                  />
```
I'm getting:

![tripwire_operations_center](https://cloud.githubusercontent.com/assets/264916/24221959/a7b47aec-0f0d-11e7-94f2-ae081835b57c.png)

I'd like to make the font size a bit smaller.

Am I missing something?

**Comment by eddier** [comment]
It looks like the graph width is being constrained in your implementation, might be worth investigating that a bit.  

We can add a prop for label size though if you think that's helpful.

**Comment by eddier** [comment]
I added a prop to deal with this on PR #58 - can you review and merge or provide feedback if necessary?
