### ISSUE TITLE
components do not pass down unhandled props

### ISSUE THREAD

**Issue by ggascoigne** [Tripwire/octagon#57]
Applying a data-hook property to a component should lead to a data-hook being reflected in the generated html.  For some components this isn't the case.

e.g.

```
                <LargeCard.Title
                  data-hook='title'
                  title={this.props.console.name}
                  description={this.props.console.friendlyName}
                />
```

**Comment by eddier** [comment]
I haven't spread props into components (using ...props) intentionally however if this is desired we can update components to pass that along which enables you to send through whatever props you want.  

In this specific example you would want to access the parent node to get the data-* attributes, for instance:

`<LargeCard.Title
                  data-hook='title'
                  title={this.props.console.name}
                  description={this.props.console.friendlyName}
                  onClick={this.handleClick}
                />

handleClick(event){
                console.log(event.target.parentNode.getAttribute('data-hook') //output is 'title'
`

**Comment by cdaringe** [comment]
one idea i have here @ggascoigne is that we make something like `rest` props that is the set difference between passes props and propTypes keys.  we would probably want some first class logic for things like className, that way classNames get added vs squashed?   not confident on the last bit, but it feels sane

**Comment by eddier** [comment]
That would probably be fine.  Alternatively if you're using ...props sparingly I doubt you'll run into any issues and can still avoid getting too sloppy.

**Comment by cdaringe** [comment]
ya, maybe so maybe so...

**Comment by eddier** [comment]
I included the ...props on the LeftNav since its possible you'll want to be passing some custom attributes in navigation.  You can check out the code on that PR #54 .  If you think a different approach is better suited for this let me know and we can adjust.

**Comment by jhegg** [comment]
Remaining todo:

- [ ] AreaChart
- [ ] BarChart
- [ ] CircleChart
- [ ] LargeCard
- [ ] MicroCard
- [ ] ThinCard
- [ ] TopNav
- [ ] Misc components at top-level of `src/components/`

**Comment by cdaringe** [comment]
this is still a partially open issue, but moving any remaining discussion to #193 now that our babel config support object-rest-spread
