### ISSUE TITLE
BarChartToolTip renders off-screen with large y-axis values

### ISSUE THREAD

**Issue by jhegg** [Tripwire/octagon#77]
If I change the y-axis value for a particular data point in the BarChart, the tooltip is rendered off-screen. For example, in the styleguide open up BarChart, show the code, and then change the y-value for the single `warning` state to 150, then mouseover the yellow/orange warning bar. The tooltip looks like this:

![barchart-tooltip-madness](https://cloud.githubusercontent.com/assets/3254856/25503340/e13e21fc-2b4e-11e7-9d9d-28356e093888.png)

If you increase the y-value to 500, the tooltip is invisible (presumably far off-screen).

Given that the height of the BarChart is fixed (in the demo it's set to 120), I don't think the tooltip placement should be based on the y-value (if that's what is causing the issue).

**Comment by cdaringe** [comment]
bummer!
