### ISSUE TITLE
BarChartToolTip mouseover area needs to be larger

### ISSUE THREAD

**Issue by jhegg** [Tripwire/octagon#78]
When mousing over the BarChart, it seems that the BarChartToolTip is only displayed when I mouseover the individual bars. If the bar is very small, for example a y-value of 1 compared to other y-values of 80, it's really difficult to mouseover the y-value 1 bar and get the tooltip to show up.

It seems like the total possible area for the bar should be tied to the mouseover, rather than the current filled area for the bar, if that makes sense.

**Comment by cdaringe** [comment]
yes, it does.  the full space allocated to each bar we should make hoverable, on behalf of the tiny bar!

**Comment by jhegg** [comment]
@eddier is awesome and this is now much better.
