### ISSUE TITLE
BarChartToolTip needs to be more customizable

### ISSUE THREAD

**Issue by jhegg** [Tripwire/octagon#79]
The BarChartToolTip seems limited in what can be presented in it. We need to display different text and icons, and right now we can only adjust the title of the tooltip. For example, we want to put some icons and different counts inside the tooltip, so even if a bar is presented with the error color, we can describe to a user the counts for normal/warning/error. For example, if the error is just a count of 1, but 50 are normal, that's important to know in the tooltip.

**Comment by eddier** [comment]
hmm how do you want to handle this?  Do you have a JSON payload that is consistent for the tooltip content?

**Comment by jhegg** [comment]
We think it's going to look something like this:

```json
[
  {
    "day": "2017-04-28T00:00:00+07:00",
    "numberOfOperations": 1,
    "numberOfErrors": 2,
    "numberOfWarnings": 1
  }
]
```

So, we will have for example the most recent 7 days of operation activity, bucketed by day (according to the browser's time zone), with the count of operations for success/warning/error status.

In the tooltip, we want to display the day ("Tuesday March 7th"), and the numbers for each status that was recorded during that day, along with their corresponding icons and color. And it looks like we want the tooltip to have a border color matching the aggregate color (with the same priority of: red error > yellow/orange warning > blue success).

![operation-activity-tooltip-mockup](https://cloud.githubusercontent.com/assets/3254856/25541767/cb0e5030-2c04-11e7-854f-cf2eac2db190.png)

I'm not sure how much is appropriate to hardcode into the tooltip, versus having it be customizable by a consumer of this library.

**Comment by eddier** [comment]
Gotcha, it might make sense to provide a default but just let the consumer of the library throw away the pre-baked tooltip content format for their own.  I'll check it out.
