### ISSUE TITLE
BarChart warning/error icons show up at different/strange vertical positions

### ISSUE THREAD

**Issue by jhegg** [Tripwire/octagon#80]
It seems like they should remain at similiar heights regardless of y-value.

![barchart-icons-vertical-madness](https://cloud.githubusercontent.com/assets/3254856/25504052/416d5014-2b51-11e7-8538-35de112d892c.png)

Increasing the y-value further makes it worse:

![barchart-icons-vertical-madness-squared](https://cloud.githubusercontent.com/assets/3254856/25504077/5878c90a-2b51-11e7-8be7-749388dfafe0.png)

**Comment by cdaringe** [comment]
ah, good call

**Comment by jhegg** [comment]
This is now fixed, thanks @eddier!
