### ISSUE TITLE
remove tripwire from class names

### ISSUE THREAD

**Issue by cdaringe** [Tripwire/octagon#85]
let's de-tripwire namespace styles.  `ui button` already indicates that we want to use the loaded SUI theme. `ui button tripwire` shouldn't be reqd

**Comment by andrewleyva** [comment]
removed 'tripwire' from css and markup. Tweaked CSS a bit to ensure default styles stick (w/o tw namespace, some specificity was removed and some places were inheriting other styles)

**Comment by cdaringe** [comment]
see #109
